#############################################################################
# Makefile for building: shapes
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  shapes.pro
# Template: app
# Command: /home/narekc/Qt5.9.7/5.9.7/gcc_64/bin/qmake -o Makefile shapes.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_3DEXTRAS_LIB -DQT_3DRENDER_LIB -DQT_3DINPUT_LIB -DQT_3DLOGIC_LIB -DQT_3DCORE_LIB -DQT_GAMEPAD_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++2a -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../Qt5.9.7/5.9.7/gcc_64/include -I../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras -I../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender -I../Qt5.9.7/5.9.7/gcc_64/include/Qt3DInput -I../Qt5.9.7/5.9.7/gcc_64/include/Qt3DLogic -I../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore -I../Qt5.9.7/5.9.7/gcc_64/include/QtGamepad -I../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets -I../Qt5.9.7/5.9.7/gcc_64/include/QtGui -I../Qt5.9.7/5.9.7/gcc_64/include/QtNetwork -I../Qt5.9.7/5.9.7/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../Qt5.9.7/5.9.7/gcc_64/mkspecs/linux-g++
QMAKE         = /home/narekc/Qt5.9.7/5.9.7/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/narekc/Qt5.9.7/5.9.7/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/narekc/Qt5.9.7/5.9.7/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = shapes1.0.0
DISTDIR = /home/narekc/magcoil/.tmp/shapes1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/narekc/Qt5.9.7/5.9.7/gcc_64/lib -Wl,-rpath-link,/home/narekc/Qt5.9.7/5.9.7/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/narekc/Qt5.9.7/5.9.7/gcc_64/lib -lQt53DExtras -lQt5Concurrent -lQt53DRender -lQt53DInput -lQt53DLogic -lQt53DCore -lQt5Gamepad -lQt5Widgets -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		scenemodifier.cpp \
		curve.cpp \
		data_helper.cpp \
		calc_thread.cpp moc_scenemodifier.cpp \
		moc_calc_thread.cpp
OBJECTS       = main.o \
		scenemodifier.o \
		curve.o \
		data_helper.o \
		calc_thread.o \
		moc_scenemodifier.o \
		moc_calc_thread.o
DIST          = ../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/unix.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/linux.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/sanitize.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/g++-base.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/qconfig.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qt_config.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/spec_post.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/toolchain.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/default_pre.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/default_post.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/warn_on.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qt.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/resources.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/moc.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/uic.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qmake_use.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/file_copies.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/exceptions.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/yacc.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/lex.prf \
		shapes.pro scenemodifier.h \
		calc_thread.h main.cpp \
		scenemodifier.cpp \
		curve.cpp \
		data_helper.cpp \
		calc_thread.cpp
QMAKE_TARGET  = shapes
DESTDIR       = 
TARGET        = shapes


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: shapes.pro ../Qt5.9.7/5.9.7/gcc_64/mkspecs/linux-g++/qmake.conf ../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/spec_pre.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/unix.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/linux.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/sanitize.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/gcc-base.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/g++-base.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/g++-unix.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/qconfig.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qt_functions.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qt_config.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/linux-g++/qmake.conf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/spec_post.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/toolchain.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/default_pre.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/resolve_config.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/default_post.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/warn_on.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qt.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/resources.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/moc.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/unix/opengl.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/uic.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/unix/thread.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qmake_use.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/file_copies.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/testcase_targets.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/exceptions.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/yacc.prf \
		../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/lex.prf \
		shapes.pro \
		../Qt5.9.7/5.9.7/gcc_64/lib/libQt53DExtras.prl \
		../Qt5.9.7/5.9.7/gcc_64/lib/libQt53DRender.prl \
		../Qt5.9.7/5.9.7/gcc_64/lib/libQt53DInput.prl \
		../Qt5.9.7/5.9.7/gcc_64/lib/libQt53DLogic.prl \
		../Qt5.9.7/5.9.7/gcc_64/lib/libQt53DCore.prl \
		../Qt5.9.7/5.9.7/gcc_64/lib/libQt5Gamepad.prl \
		../Qt5.9.7/5.9.7/gcc_64/lib/libQt5Widgets.prl \
		../Qt5.9.7/5.9.7/gcc_64/lib/libQt5Gui.prl \
		../Qt5.9.7/5.9.7/gcc_64/lib/libQt5Network.prl \
		../Qt5.9.7/5.9.7/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile shapes.pro
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/spec_pre.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/unix.conf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/linux.conf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/sanitize.conf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/gcc-base.conf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/gcc-base-unix.conf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/g++-base.conf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/common/g++-unix.conf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/qconfig.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_core.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_help.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_location.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_network.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_script.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qt_functions.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qt_config.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/linux-g++/qmake.conf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/spec_post.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/exclusive_builds.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/toolchain.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/default_pre.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/resolve_config.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/default_post.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/warn_on.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qt.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/resources.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/moc.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/unix/opengl.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/uic.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/unix/thread.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/qmake_use.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/file_copies.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/testcase_targets.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/exceptions.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/yacc.prf:
../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/lex.prf:
shapes.pro:
../Qt5.9.7/5.9.7/gcc_64/lib/libQt53DExtras.prl:
../Qt5.9.7/5.9.7/gcc_64/lib/libQt53DRender.prl:
../Qt5.9.7/5.9.7/gcc_64/lib/libQt53DInput.prl:
../Qt5.9.7/5.9.7/gcc_64/lib/libQt53DLogic.prl:
../Qt5.9.7/5.9.7/gcc_64/lib/libQt53DCore.prl:
../Qt5.9.7/5.9.7/gcc_64/lib/libQt5Gamepad.prl:
../Qt5.9.7/5.9.7/gcc_64/lib/libQt5Widgets.prl:
../Qt5.9.7/5.9.7/gcc_64/lib/libQt5Gui.prl:
../Qt5.9.7/5.9.7/gcc_64/lib/libQt5Network.prl:
../Qt5.9.7/5.9.7/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile shapes.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents scenemodifier.h calc_thread.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp scenemodifier.cpp curve.cpp data_helper.cpp calc_thread.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++2a -O2 -Wall -W -dM -E -o moc_predefs.h ../Qt5.9.7/5.9.7/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_scenemodifier.cpp moc_calc_thread.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_scenemodifier.cpp moc_calc_thread.cpp
moc_scenemodifier.cpp: ../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QObject \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobject.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qglobal.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qconfig.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlogging.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qflags.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmutex.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstring.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qchar.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qiterator.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qpair.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qregexp.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qentity.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnode.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnodecreatedchange.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qscenechange.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnodeid.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qt3dcore_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QDebug \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qdebug.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qhash.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmap.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlocale.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvariant.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvector.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qpoint.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qset.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QHashFunctions \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QSharedPointer \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QMetaType \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qtransform.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qcomponent.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qtguiglobal.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qtgui-config.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qvector3d.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qvector4d.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qquaternion.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qrect.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmargins.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsize.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QTorusMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qtorusmesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qt3dextras_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qgeometryrenderer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qgeometry.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qt3drender_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QConeMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qconemesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QCylinderMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qcylindermesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QCuboidMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qcuboidmesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QSize \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QPlaneMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qplanemesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QSphereMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qspheremesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QPhongMaterial \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qphongmaterial.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qmaterial.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QVariant \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QColor \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qcolor.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qrgb.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qrgba64.h \
		scenemodifier.h \
		moc_predefs.h \
		../Qt5.9.7/5.9.7/gcc_64/bin/moc
	/home/narekc/Qt5.9.7/5.9.7/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/mkspecs/linux-g++ -I/home/narekc/magcoil -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/Qt3DInput -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/Qt3DLogic -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/QtGamepad -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/QtWidgets -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/QtGui -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/QtNetwork -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include scenemodifier.h -o moc_scenemodifier.cpp

moc_calc_thread.cpp: ../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QObject \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobject.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qglobal.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qconfig.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlogging.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qflags.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmutex.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstring.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qchar.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qiterator.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qpair.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qregexp.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QThread \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qthread.h \
		ratio_mag_model.hpp \
		mag_model.hpp \
		mag_suspension.hpp \
		consts.hpp \
		steel.hpp \
		curve.hpp \
		data_helper.hpp \
		susp_data.hpp \
		simple_mag_model.hpp \
		calc_thread.h \
		moc_predefs.h \
		../Qt5.9.7/5.9.7/gcc_64/bin/moc
	/home/narekc/Qt5.9.7/5.9.7/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/mkspecs/linux-g++ -I/home/narekc/magcoil -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/Qt3DInput -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/Qt3DLogic -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/QtGamepad -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/QtWidgets -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/QtGui -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/QtNetwork -I/home/narekc/Qt5.9.7/5.9.7/gcc_64/include/QtCore -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include calc_thread.h -o moc_calc_thread.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp scenemodifier.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QObject \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobject.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qglobal.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qconfig.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlogging.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qflags.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmutex.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstring.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qchar.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qiterator.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qpair.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qregexp.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qentity.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnode.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnodecreatedchange.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qscenechange.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnodeid.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qt3dcore_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QDebug \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qdebug.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qhash.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmap.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlocale.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvariant.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvector.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qpoint.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qset.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QHashFunctions \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QSharedPointer \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QMetaType \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qtransform.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qcomponent.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qtguiglobal.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qtgui-config.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qvector3d.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qvector4d.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qquaternion.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qrect.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmargins.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsize.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QTorusMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qtorusmesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qt3dextras_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qgeometryrenderer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qgeometry.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qt3drender_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QConeMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qconemesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QCylinderMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qcylindermesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QCuboidMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qcuboidmesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QSize \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QPlaneMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qplanemesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QSphereMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qspheremesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QPhongMaterial \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qphongmaterial.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qmaterial.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QVariant \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QColor \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qcolor.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qrgb.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qrgba64.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QGuiApplication \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qguiapplication.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcoreapplication.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qeventloop.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qwindowdefs.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qwindowdefs_win.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qinputmethod.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qcamera.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qcameralens.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QMatrix4x4 \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QQuaternion \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QVector3D \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/QApplication \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qapplication.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qcursor.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qwidget.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qpaintdevice.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qpalette.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qbrush.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qmatrix.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qpolygon.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qregion.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qline.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qtransform.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qpainterpath.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qimage.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qpixelformat.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qpixmap.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qfont.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qfontmetrics.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qfontinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qsizepolicy.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qkeysequence.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qevent.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qurl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qurlquery.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qfile.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qfiledevice.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qvector2d.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qtouchdevice.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/QWidget \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/QHBoxLayout \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qboxlayout.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qlayout.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qlayoutitem.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qgridlayout.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/QCheckBox \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qcheckbox.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qabstractbutton.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qicon.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/QCommandLinkButton \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qcommandlinkbutton.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qpushbutton.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QScreen \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qscreen.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QList \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QRect \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QSizeF \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QTransform \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DInput/QInputAspect \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DInput/qinputaspect.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DInput/qt3dinput_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qabstractaspect.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qmesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QUrl \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qtechnique.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qrenderpass.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qshaderprogram.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qrenderstate.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qfilterkey.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QHash \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QVector \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qeffect.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qtexture.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qtextureimagedata.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QOpenGLTexture \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qopengltexture.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qopengl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qt_windows.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qopengles2ext.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qopenglext.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QScopedPointer \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QImage \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qtexturewrapmode.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qtextureimage.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qabstracttextureimage.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qabstracttexture.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qtextureimagedatagenerator.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qabstractfunctor.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qsceneloader.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qpointlight.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qabstractlight.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qaspectengine.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qrenderaspect.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qforwardrenderer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qtechniquefilter.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qframegraphnode.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QRectF \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qt3dwindow.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QWindow \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qwindow.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QEvent \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QMargins \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qsurface.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qsurfaceformat.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QOrbitCameraController \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qorbitcameracontroller.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/QEntity \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/QSlider \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qslider.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qabstractslider.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/QLabel \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qlabel.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtWidgets/qframe.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

scenemodifier.o: scenemodifier.cpp scenemodifier.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QObject \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobject.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qglobal.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qconfig.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlogging.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qflags.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmutex.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstring.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qchar.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qiterator.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qpair.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qregexp.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qentity.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnode.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnodecreatedchange.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qscenechange.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnodeid.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qt3dcore_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QDebug \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qdebug.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qhash.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmap.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlocale.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvariant.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvector.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qpoint.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qset.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QHashFunctions \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QSharedPointer \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QMetaType \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qtransform.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qcomponent.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qtguiglobal.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qtgui-config.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qvector3d.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qvector4d.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qquaternion.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qrect.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmargins.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsize.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QTorusMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qtorusmesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qt3dextras_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qgeometryrenderer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qgeometry.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qt3drender_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QConeMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qconemesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QCylinderMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qcylindermesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QCuboidMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qcuboidmesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QSize \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QPlaneMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qplanemesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QSphereMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qspheremesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QPhongMaterial \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qphongmaterial.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qmaterial.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QVariant \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QColor \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qcolor.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qrgb.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qrgba64.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QMetalRoughMaterial \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qmetalroughmaterial.h \
		calc_thread.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QThread \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qthread.h \
		ratio_mag_model.hpp \
		mag_model.hpp \
		mag_suspension.hpp \
		consts.hpp \
		steel.hpp \
		curve.hpp \
		data_helper.hpp \
		susp_data.hpp \
		simple_mag_model.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scenemodifier.o scenemodifier.cpp

curve.o: curve.cpp curve.hpp \
		lagranj.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o curve.o curve.cpp

data_helper.o: data_helper.cpp data_helper.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data_helper.o data_helper.cpp

calc_thread.o: calc_thread.cpp scenemodifier.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QObject \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobject.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobjectdefs.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qnamespace.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qglobal.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qconfig.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtcore-config.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsystemdetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qprocessordetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcompilerdetection.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtypeinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsysinfo.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlogging.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qflags.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbasicatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qgenericatomic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_cxx11.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qatomic_msvc.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qglobalstatic.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmutex.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qnumeric.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qversiontagging.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstring.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qchar.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbytearray.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qrefcount.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qarraydata.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringbuilder.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qalgorithms.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qiterator.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qhashfunctions.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qpair.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qbytearraylist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringlist.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qregexp.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qstringmatcher.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcoreevent.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qscopedpointer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmetatype.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvarlengtharray.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcontainerfwd.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qobject_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qentity.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnode.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnodecreatedchange.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qscenechange.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qnodeid.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qt3dcore_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QDebug \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qdebug.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qhash.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmap.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qtextstream.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qiodevice.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qlocale.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvariant.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qshareddata.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qvector.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qpoint.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qset.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qcontiguouscache.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsharedpointer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QHashFunctions \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QSharedPointer \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QMetaType \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qtransform.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DCore/qcomponent.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qmatrix4x4.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qtguiglobal.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qtgui-config.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qvector3d.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qvector4d.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qquaternion.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qgenericmatrix.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qdatastream.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qrect.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qmargins.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/qsize.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QTorusMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qtorusmesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qt3dextras_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qgeometryrenderer.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qgeometry.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qt3drender_global.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QConeMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qconemesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QCylinderMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qcylindermesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QCuboidMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qcuboidmesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QSize \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QPlaneMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qplanemesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QSphereMesh \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qspheremesh.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/QPhongMaterial \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DExtras/qphongmaterial.h \
		../Qt5.9.7/5.9.7/gcc_64/include/Qt3DRender/qmaterial.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtCore/QVariant \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/QColor \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qcolor.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qrgb.h \
		../Qt5.9.7/5.9.7/gcc_64/include/QtGui/qrgba64.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o calc_thread.o calc_thread.cpp

moc_scenemodifier.o: moc_scenemodifier.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scenemodifier.o moc_scenemodifier.cpp

moc_calc_thread.o: moc_calc_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_calc_thread.o moc_calc_thread.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

